package com.coperatecoding.secodeverseback.domain;

public enum Major {
    ELECTRONIC_ENGINEERING, //전자공학부
    ARCHITECTURE, //건축학부
    INDUSTRIAL_ENGINEERING, //산업공학부
    POLYMER_SCIENCE_AND_ENGINEERING, //고분자공학과
    MATERIALS_DESIGN_ENGINEERING, //소재디자인공학과
    CHEMICAL_ENGINEERING, //화학공학과
    MATERIALS_SCIENCE_AND_ENGINEERING, //신소재공학부
    MECHANICAL_ENGINEERING, //기계공학과
    MECHANICAL_DESIGN_ENGINEERING, //기계설계공학과
    MECHANICAL_SYSTEM_ENGINEERING, //기계시스템공학과
    CIVIL_ENGINEERING, //토목공학과
    COMPUTER_ENGINEERING, //컴퓨터공학과
    COMPUTER_SOFTWARE_ENGINEERING, //컴퓨터소프트웨어공학과
    OPTICAL_ENGINEERING, //광시스템공학과
    MEDICAL_IT_CONVERGENCE_ENGINEERING, //메디컬IT융합공학과
    ENVIRONMENTAL_ENGINEERING, //환경공학과
    IT_CONVERGENCE, //IT융합학과
    ARTIFICIAL_INTELLIGENCE_ENGINEERING, //인공지능공학과
    MATHEMATICS_AND_BIGDATA_SCIENCE, //수리빅데이터학과
    CHEMISTRY_AND_BIO_SCIENCE, //화학생명과학과
    BUSINESS_ADMINISTRATION //경영학과
}
