spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SEcodeVerse?serverTimezone=Asia/Seoul
    username: coco
    password: Coco1@2@3@4

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
